### ISSUE TITLE
The test is failing.

### ISSUE THREAD

**Issue by hillscottc** [BTMPL/react-on#1]
```
$ npm test

> react-on@1.0.0 test /Users/hills120/dev/temp
> jest

 FAIL  src/Demo/__test__/Demo.test.js
  ● Test suite failed to run

    /Users/hills120/dev/react-on/src/Demo/__test__/Demo.test.js: Unexpected token (7:12)
         5 | describe("<Demo />", () => {
         6 |   it("should render", () => {
      >  7 |     shallow(<Demo />);
           |             ^
         8 |   });
         9 | });
        10 | 

Test Suites: 1 failed, 1 total
```

**Comment by BTMPL** [comment]
Hello - thanks for pointing that out, looks like jest is not seeing the config for bable since I moved it to webpack config.

**Comment by BTMPL** [comment]
A workaround for now is to create `.babelrc` with the config for babel:

```
{
  "presets": ["es2015", "react"],
  "plugins": ["babel-plugin-transform-class-properties"]
}
```

**Comment by hillscottc** [comment]
Yup, that fixes it. Thanks! This is very helpful.

**Comment by BTMPL** [comment]
Sadly, jest can't use webpack config for babel presets :( Only way currently is using .babelrc so I re-added it to the project.

**Comment by hillscottc** [comment]
Or in the package.json either, eh? I was expecting to find it configured there, like in the tweet you referenced. I even gave that a quick try -- but no luck.
