### ISSUE TITLE
About directory-named-webpack-plugin

### ISSUE THREAD

**Issue by hillscottc** [BTMPL/react-on#2]
I'm curious about your inclusion of directory-named-webpack-plugin. The docs tell me "This plugin makes it possible to control what file within directory will be treated as entry file." That feels quirky. Would I want JS to work differently in this way for certain projects? It feels like one more thing to I'd have to remember when trying to reuse code in a project 'packed _without_ this plugin.

**Comment by hillscottc** [comment]
Looking around, I see it's incredibly common. I'd been using it myself in a couple other boilerplates and hadn't even noticed it. I've learned something new. :)

**Comment by BTMPL** [comment]
It is very handy especially when you have a deep folder structure and like to keep files named as the component/directory so your IDE can show the file name in tab, and not only "index.js".

You are right - if you're going to make components reusable it might be better to assume the end-user is not using this and supply the full path everywhere, but seeing how small footprint this plugin has (2 direct dependencies) I would recommend it for your projects :)
